import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, FileSpreadsheet, Loader2, RefreshCw } from "lucide-react";

const line = "#dce5e2"; const teal = "#087f8c";
async function api<T>(url: string): Promise<T> { const r = await fetch(url, { credentials: "include" }); if (!r.ok) { let m = "Unable to load report"; try { const b = await r.json(); m = b.error || b.message || m; } catch { /* non-json */ } throw new Error(m); } return r.json(); }
const money = (v: unknown) => Number(v || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
function safe(v: unknown) { const s = String(v ?? ""); return /^[=+\-@]/.test(s) ? `'${s}` : s; }
function download(name: string, headers: string[], rows: unknown[][]) { const text = [headers, ...rows].map(row => row.map(v => `"${safe(v).replaceAll('"', '""')}"`).join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([text], { type: "text/csv" })); a.download = `${name}.csv`; a.click(); URL.revokeObjectURL(a.href); }
const fmt = (v?: string) => v ? new Date(v).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—";

export default function TallyFinanceReport() {
  const path = window.location.pathname; const report = path.includes("profit-loss") ? "pl" : path.includes("outstanding") ? "outstanding" : "bank";
  const title = report === "pl" ? "Profit & loss" : report === "outstanding" ? "Outstanding bills" : "Bank reconciliation";
  const today = new Date().toISOString().slice(0, 10); const [fromDate, setFrom] = useState(`${new Date().getFullYear()}-04-01`); const [toDate, setTo] = useState(today); const [asOfDate, setAsOf] = useState(today); const [partyType, setParty] = useState("customer"); const [bankGlId, setBank] = useState("");
  const options = useQuery<any>({ queryKey: ["/api/tally/master-options"], queryFn: () => api<any>("/api/tally/master-options"), enabled: report === "bank" });
  const bankLedgers = (options.data?.generalLedgers || []).filter((x: any) => String(x.gl_type || x.glType).toLowerCase().includes("bank"));
  useEffect(() => { if (!bankGlId && bankLedgers[0]) setBank(bankLedgers[0].id); }, [bankGlId, bankLedgers]);
  const url = report === "pl" ? `/api/tally/reports/profit-loss?fromDate=${encodeURIComponent(fromDate)}&toDate=${encodeURIComponent(toDate)}` : report === "outstanding" ? `/api/tally/reports/outstanding?partyType=${encodeURIComponent(partyType)}&asOfDate=${encodeURIComponent(asOfDate)}` : `/api/tally/reports/bank-reconciliation?bankGlId=${encodeURIComponent(bankGlId)}&fromDate=${encodeURIComponent(fromDate)}&toDate=${encodeURIComponent(toDate)}`;
  const q = useQuery<any>({ queryKey: [url], queryFn: () => api<any>(url), enabled: report !== "bank" || !!bankGlId });
  const data = q.data || {};
  const plRows = [...(data.income || []).map((r: any) => ({ ...r, section: "Income" })), ...(data.expense || []).map((r: any) => ({ ...r, section: "Expense" }))];
  const rows = report === "pl" ? plRows : report === "outstanding" ? data.parties || [] : [...(data.bookTransactions || []).map((r: any) => ({ ...r, section: "Book transaction" })), ...(data.reconRecords || []).map((r: any) => ({ ...r, section: "Reconciliation" }))];
  const headers = report === "pl" ? ["Section", "Ledger", "Amount"] : report === "outstanding" ? ["Party", "Ledger type", "Balance", "Closing balance"] : ["Section", "Bank / voucher", "Date", "Amount", "Status"];
  const csvRows = rows.map((r: any) => report === "pl" ? [r.section, r.ledger_name || r.name || r.ledger || r.account, r.net_credit || r.net_debit] : report === "outstanding" ? [r.party_name || r.name || r.party, r.gl_type, r.balance, r.closing_balance] : [r.section, r.bank_ledger_name || r.voucher_no || r.narration, r.statement_date || r.voucher_date, r.amount || r.statement_balance || r.book_balance, r.recon_status]);
  const totals = report === "pl" ? [["Total income", data.totalIncome], ["Total expense", data.totalExpense], ["Net profit", data.netProfit]] : report === "bank" ? [["Book total debit", data.bookTotalDr], ["Book total credit", data.bookTotalCr], ["Book balance", data.bookBalance]] : [];
  const summary = useMemo(() => totals, [data]);
  return <div className="min-h-full p-3 md:p-5" style={{ background: "#f6f4ef", color: "#16323a" }}><div className="mx-auto max-w-[1450px] overflow-hidden rounded-xl border bg-white" style={{ borderColor: line }}>
    <header className="flex flex-wrap items-end justify-between gap-4 border-b p-5" style={{ borderColor: line }}><div><div className="text-[11px] font-bold uppercase tracking-[.16em]" style={{ color: teal }}>Tally finance report</div><h1 className="mt-1 text-2xl font-bold">{title}</h1><p className="mt-1 text-sm text-[#668087]">Source: {data.sourceMetadata?.source || "Pioneer Prism / Tally bridge"} · Last sync: {fmt(data.lastTallySyncAt || data.last_tally_sync)}</p></div><div className="flex gap-2"><button onClick={() => q.refetch()} className="rounded-lg border p-2" style={{ borderColor: line }}><RefreshCw size={16} className={q.isFetching ? "animate-spin" : ""} /></button><button onClick={() => download(title.replaceAll(" ", "-"), headers, csvRows)} className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold text-white" style={{ background: teal }}><Download size={15} />CSV</button></div></header>
    <div className="flex flex-wrap items-end gap-3 border-b bg-[#fbfcfa] p-4" style={{ borderColor: line }}>{report === "outstanding" ? <><label className="text-xs font-bold text-[#668087]">PARTY TYPE<select value={partyType} onChange={e => setParty(e.target.value)} className="mt-1 block h-9 rounded-lg border px-3 text-sm" style={{ borderColor: line }}><option value="customer">Customers / receivable</option><option value="supplier">Suppliers / payable</option></select></label><label className="text-xs font-bold text-[#668087]">AS OF<input type="date" value={asOfDate} onChange={e => setAsOf(e.target.value)} className="mt-1 block h-9 rounded-lg border px-3 text-sm" style={{ borderColor: line }} /></label></> : <><label className="text-xs font-bold text-[#668087]">FROM<input type="date" value={fromDate} onChange={e => setFrom(e.target.value)} className="mt-1 block h-9 rounded-lg border px-3 text-sm" style={{ borderColor: line }} /></label><label className="text-xs font-bold text-[#668087]">TO<input type="date" value={toDate} onChange={e => setTo(e.target.value)} className="mt-1 block h-9 rounded-lg border px-3 text-sm" style={{ borderColor: line }} /></label>{report === "bank" && <label className="text-xs font-bold text-[#668087]">BANK LEDGER<select value={bankGlId} onChange={e => setBank(e.target.value)} className="mt-1 block h-9 rounded-lg border px-3 text-sm" style={{ borderColor: line }}><option value="">All bank ledgers</option>{bankLedgers.map((b: any) => <option key={b.id} value={b.id}>{b.name || b.ledger_name}</option>)}</select></label>}</>}</div>
    {q.isLoading ? <div className="p-16 text-center text-sm text-[#789096]"><Loader2 size={22} className="mx-auto mb-2 animate-spin" />Loading report</div> : q.isError ? <div className="p-16 text-center text-sm text-[#a63f27]">{(q.error as Error).message}</div> : rows.length === 0 ? <div className="p-16 text-center text-sm text-[#789096]"><FileSpreadsheet size={24} className="mx-auto mb-2 opacity-40" />No rows for this selection.</div> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#edf2ef] text-left text-[11px] uppercase tracking-wider text-[#668087]"><tr>{headers.map(h => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((r: any, i: number) => <tr key={r.id || i} className="border-t hover:bg-[#f7faf8]" style={{ borderColor: line }}>{(report === "pl" ? [r.section, r.ledger_name || r.name || r.ledger || r.account, money(r.section === "Income" ? r.net_credit : r.net_debit)] : report === "outstanding" ? [r.party_name || r.name || r.party, r.gl_type || "—", money(r.balance), money(r.closing_balance)] : [r.section, r.bank_ledger_name || r.voucher_no || r.narration || "—", r.statement_date || r.voucher_date || "—", money(r.amount || r.statement_balance || r.book_balance), r.recon_status || "—"]).map((v: any, j: number) => <td key={j} className={`px-5 py-3 ${((j === 2 && report === "pl") || (j === 3 && report === "bank")) ? "text-right font-mono" : ""}`}>{v}</td>)}</tr>)}</tbody></table></div>}
    {summary.length > 0 && <footer className="flex flex-wrap gap-6 border-t bg-[#edf2ef] p-4 text-sm font-bold" style={{ borderColor: line }}>{summary.map(([k, v]: any) => <span key={k}>{String(k).replaceAll("_", " ")}: <b style={{ color: teal }}>{money(v)}</b></span>)}</footer>}{data.disclaimer && <div className="border-t p-4 text-xs text-[#80672c]">Disclaimer: {data.disclaimer}</div>}
  </div></div>;
}